services:
  - type: web
    name: slack-bolt-app
    env: docker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/project/src/.playwright"
